server:
  port: 8005

spring:
  application:
    name: GatewayEmpMngmt
  
  cloud:
    gateway:
      routes:
      - id: Employee
      - uri: http://localhost:5555
        predicates:
          - Path=/employee/**
        
      - id: Employee-Training
      - uri: http://localhost:4444
        predicates:
          - Path=/employee/**
